docs/changelog.md
=> Import release notes for 0.69.1

docs/adopters.md, sync.sh
for easier editing without a full CI cycle for #11
=> move adopters file from kube-rs repo to this

docs/architecture.md, docs/governance.md, docs/maintainers.md, sync.sh
via kube-rs/kube-rs#868 for #11 
needs a sync commit after kube-rs pr lands.
=> move architecture + maintainers + governance to this repo

docs/controllers/object.md
Signed-off-by: Mahesh Rayas <maheshrayas@gmail.com>
=> fix typo of object name

docs/adopters.md
Signed-off-by: 牧心 <chengqinglin@icloud.com>
=> Add adopter: kubectl-watch

docs/adopters.md
Hi! Let me know if I missed anything.
=> Add Databricks operator to adopters

docs/controllers/testing.md, includes/abbreviations.md, includes/links.md, mkdocs.yml
after much updating in controller-rs finally have something to say about this.
=> Controller testing guidelines

docs/controllers/security.md, mkdocs.yml
kind of my line of work, but will ask channel for nitpicking or issues.
=> Basic security guide for controllers

docs/adopters.md
Signed-off-by: Aviram Hassan <aviram@metalbear.co>
=> add mirrord and metalbear to adopters

docs/controllers/observability.md, docs/controllers/reconciler.md, docs/controllers/relations.md
Also add a link to first appearance of HPA
=> fix a couple of typos

docs/guides.md, mkdocs.yml
I thought it'd be nice to have a collection of third party guides/tutorials!
=> add guides/tutorials section

docs/adopters.md
=> Add xline-operator to adopters

docs/controllers/gc.md, includes/links.md, mkdocs.yml
Feel like i've explained GC to a good couple of handful of people at this point, so want to have a doc to point to.
=> Add a controller doc about garbage collection

docs/adopters.md
=> Update CoreDB to Tembo

docs/controllers/manifests.md, docs/controllers/security.md, mkdocs.yml
In response to people asking about rbac generation and netpols.
Particularly, it's inspired by https://github.com/kube-rs/kube/issues/1115
=> Add a manifests section to help people deploying

docs/adopters.md
xline operator is writing with golang now, so delete the adopter of xline operator (:
=> Remove the adopter of xline operator.

docs/adopters.md
This PR adds a project called rūnō to the list of adopters.
=> feat: add runo to adopters

docs/adopters.md
Request to add the open-source project Akri to the adopters list.
=> Adding project Akri to the adopters.md

docs/features.md, includes/links.md, mkdocs.yml
quick doc to write. cargo.toml is not super helpful to clarify what you get and why, so thought to write a quick one.
=> Document Features

docs/adopters.md
SimKube: https://github.com/acrlabs/simkube
Blog post announcing v1.0: https://blog.appliedcomputing.io/p/announcing-simkube-v10
=> Add SimKube to adopters

docs/features.md, includes/links.md
for https://github.com/kube-rs/kube/pull/1323 when it releases
=> Add feature docs for webpki-roots

docs/guides.md
Details can be found in [this PR](https://github.com/kube-rs/kube/pull/1638)
=> Introducing AI Agent section along with kube-rs Guru in guides.md

docs/adopters.md
Add Cluster API Addon Provider Fleet and crust-gather to the list of adopters.
=> Add crust-gather and CAAPF to the adopters

docs/profiling.md, mkdocs.yml
based on a question that popped up. this works great on linux.
=> profiling stub

docs/controllers/admission.md
Add documentation for recent changes, introducing `KubeSchema` derive macro:
- https://github.com/kube-rs/kube/pull/1754
- https://github.com/kube-rs/kube/pull/1750
=> Add documentation for the `KubeSchema` derive macro

docs/stability.md
Some stuff pretty out of date there. Particularly the "we have not yet released the 1.0" part.
Tried to roughly say what we have been saying in preparation for the 1.0 release; align breaks with k8s-openapi, but still follow existing setups.
Have also updated the "deprecated strategy" from "3 releases" to "3 major releases" now that we have started bumping majors.
=> Revamp stability doc for major releases
